version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:14
    working_directory: ~/application
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/application
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/application
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Deploy
          command: |
            yarn build && yarn deploy
workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only:
                - master