version: 2.1
jobs:
  setup:
    docker:
      - image: cimg/node:14.17.1
    working_directory: ~/application
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ed:06:24:e7:dd:52:8b:12:44:a5:b6:42:c9:ea:84:a0"
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/application
  build:
    docker:
      - image: cimg/node:14.17.1
    working_directory: ~/application
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "ed:06:24:e7:dd:52:8b:12:44:a5:b6:42:c9:ea:84:a0"
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            git config user.email "8767154@gmail.com"
            git config user.name "takashi-154"
            yarn build && yarn deploy
workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only:
                - master